# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-09-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colony', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u96c6\u7fa4')),
                ('nose', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u673a\u5934')),
                ('serial_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('nose_manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u673a\u5934\u7ba1\u7406ip')),
                ('colony_manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u96c6\u7fa4\u7ba1\u7406ip')),
                ('service_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u670d\u52a1ip')),
                ('computer_room', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u623f')),
                ('frame', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u67b6')),
                ('purpose', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7528\u9014')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u578b\u53f7')),
                ('environmental', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u73af\u5883')),
                ('warranty_level', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4fdd\u4fee\u7ea7\u522b')),
                ('landing_mode', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u767b\u9646\u65b9\u5f0f')),
                ('subordinate_departments', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('produce_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6295\u4ea7\u65e5\u671f')),
            ],
            options={
                'db_table': 'produce_nas',
            },
        ),
        migrations.CreateModel(
            name='Producesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u540d\u79f0')),
                ('serial_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7ba1\u7406ip')),
                ('computer_room', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u623f')),
                ('frame', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u67b6')),
                ('purpose', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7528\u9014')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u578b\u53f7')),
                ('environmental', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u73af\u5883')),
                ('warranty_level', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4fdd\u4fee\u7ea7\u522b')),
                ('landing_mode', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u767b\u9646\u65b9\u5f0f')),
                ('subordinate_departments', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('produce_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6295\u4ea7\u65e5\u671f')),
                ('example_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b9e\u4f8b\u53f7')),
                ('examples', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u5b9e\u4f8b\u72b6')),
                ('instance_port', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b9e\u4f8b\u7aef\u53e3')),
            ],
            options={
                'db_table': 'produce_san',
            },
        ),
        migrations.CreateModel(
            name='Testnas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colony', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u96c6\u7fa4')),
                ('nose', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u673a\u5934')),
                ('serial_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('nose_manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u673a\u5934\u7ba1\u7406ip')),
                ('colony_manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u96c6\u7fa4\u7ba1\u7406ip')),
                ('service_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u670d\u52a1ip')),
                ('computer_room', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u623f')),
                ('frame', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u67b6')),
                ('purpose', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7528\u9014')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u578b\u53f7')),
                ('environmental', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u73af\u5883')),
                ('warranty_level', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4fdd\u4fee\u7ea7\u522b')),
                ('landing_mode', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u767b\u9646\u65b9\u5f0f')),
                ('produce_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6295\u4ea7\u65e5\u671f')),
            ],
            options={
                'db_table': 'test_nas',
            },
        ),
        migrations.CreateModel(
            name='Testsan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u540d\u79f0')),
                ('serial_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7ba1\u7406ip')),
                ('computer_room', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u623f')),
                ('frame', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u67b6')),
                ('purpose', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7528\u9014')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u578b\u53f7')),
                ('environmental', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u73af\u5883')),
                ('warranty_level', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4fdd\u4fee\u7ea7\u522b')),
                ('landing_mode', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u767b\u9646\u65b9\u5f0f')),
                ('subordinate_departments', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('produce_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6295\u4ea7\u65e5\u671f')),
            ],
            options={
                'db_table': 'test_san',
            },
        ),
    ]
