# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-09-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsan',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='testsan',
            name='serial_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5e8f\u5217\u53f7'),
        ),
    ]
