# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-09-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190903_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnas',
            name='service_ip',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u670d\u52a1ip'),
        ),
    ]
