# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-09-03 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldevlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nasaggregate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nascluster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nasnode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nasvolume',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nasvserver',
            options={'managed': False},
        ),
    ]
